### ISSUE TITLE
Input data for microarray

### ISSUE THREAD

**Issue by leolambb** [sunduanchen/Scissor#10]
Hi,

Thanks for developing this great tool!
I am wondering what  kind of microarray data should be used as input for Scissor. Will RMA normalized data without log transformed be acceptable? Thanks in advance!

Best,
Leo Lam

**Comment by sunduanchen** [comment]
Hi Leo,

For the bulk normalization, we didn't require the specific normalization technique. You can try log transform for your bulk data. Please noticed that the log transformed data may obtain lower correlations between bulk samples and single cells. You can consider another type of bulk normalization of the correlations are too low (near zero).

Best,
Duanchen
