### ISSUE TITLE
Crash happens when performing Scissor on Rstudio Server

### ISSUE THREAD

**Issue by mitraclip** [sunduanchen/Scissor#12]
Thank you for developing such a powerful tool. 
I run the Scissor function after loading files needed. But several times the function stopped in the state which is shown in the snapshot. And it only returned the result used for next step regression. I also found that the rstudio server crashed when this function is run in the stage as shown in the snapshot.  I guessed there might be something unmatched.
![129429979536314360](https://user-images.githubusercontent.com/76574724/145681852-67c9c50e-cd56-4050-877c-2f6079318913.jpg)

**Comment by sunduanchen** [comment]
Can your share your data with me?

I wonder it may caused by the big size of your data.

**Comment by mitraclip** [comment]
Thank you for your kind cooperation. Could you give me your common email address? 

Best 
Yuxing Chen

**Comment by sunduanchen** [comment]
My email address is sunduanchen@gmail.com

Best,
Duanchen

**Comment by shawnchizari** [comment]
Hi Duanchen,

I am running into the same issue where R studio crashes at the same stage. I do not have an output aside from the save file that is generated on line 125 of Scissor.R. I am working with small single cell and bulk datasets, and I even tried downsampling my Seurat object to 500 cells, but I still encounter this crash.

**Comment by mitraclip** [comment]
> Hi Duanchen,
> 
> I am running into the same issue where R studio crashes at the same stage. I do not have an output aside from the save file that is generated on line 125 of Scissor.R. I am working with small single cell and bulk datasets, and I even tried downsampling my Seurat object to 500 cells, but I still encounter this crash.

Yes, I also downsampled my data and the size of my data is smaller than the data in tutorial.

**Comment by sunduanchen** [comment]
Hi Yuxing and Shawn,

I made an update to debug this. Please let me know if it works on your data.

Best,
Duanchen
