### ISSUE TITLE
What the mean of "X","Y", and "network" variables in reliability.test  function

### ISSUE THREAD

**Issue by Famingzhao** [sunduanchen/Scissor#13]
Hi!
Thanks for the great tools!
When I read the Scissor Tutorial of section "Reliability significance test", I was confused about "result1 <- reliability.test(X, Y, network, alpha = 0.05, family = "cox", cell_num = numbers, n = 10, nfold = 10)". 
Where can I get the value of "X","Y", and "network"? I only know "numbers" are from "infos1" variable.
Best,
Faming

**Comment by Famingzhao** [comment]
load('Scissor_LUAD_survival.RData') is needed.

**Comment by sunduanchen** [comment]
Yes. The saved Rdata in Scissor can be used as the test inputs.

Thanks,
Duanchen
