### ISSUE TITLE
Including covariates in coxph regression

### ISSUE THREAD

**Issue by grst** [sunduanchen/Scissor#14]
Thanks for developing this tool! I've been running scissor on some lung cancer data and the results are quite promising! 

I have a question regarding using the survival data: 
The survival is obviously highly confounded by the tumor stage. I get highly similar results when running scissor with survival data and with binary early stage/late stage data. Is there a way to include the tumor stage, or other covariates such as age, into the Cox-regression model, such that I can find cell-types that are associated with better survival independent of the tumor stage?

**Comment by sunduanchen** [comment]
Hi,

We cannot directly achieve this goal in our current scissor model. In our paper, we found the same observation that using survival (cox regression) and pathological stage (linear regression) can lead to similar cell subpopulations.

We will work on this to see whether scissor can identify some phenotype-specific subpopulations.

Thanks,
Duanchen
