### ISSUE TITLE
Tag for continuous phenotype

### ISSUE THREAD

**Issue by xiaoyaohao** [sunduanchen/Scissor#17]
Hi!
Thank you for the nice tools.
I was wondering what should the tag be like if I use Scissor for a continuous phenotype, like tumor size in the follow image?
![name](https://user-images.githubusercontent.com/48345770/149107306-981f55ca-1974-479f-b263-e13d010e0ab3.png)
I use:
Z = table(pheno$TumorSizeMax)
tag = names(Z)
The code works, but I get neither Scissor positive nor negative cells.
Is the tag correct for linear regression?
Thanks very much!

**Comment by hyjforesight** [comment]
Hi @xiaoyaohao 
Could you tell us whether this tag is correct for linear regression?
Thanks!
