### ISSUE TITLE
R Session Aborted when running Scissor

### ISSUE THREAD

**Issue by Eddylyf** [sunduanchen/Scissor#18]
Hi Duanchen,
Thanks for developing this interesting tools to discover important cell populations according to bulk data and scRNA-seq data! I met some issues and cannot run my own datasets: when I run Scissor on my created object, the error of "Scissor" step is "Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  :   'data' must be of a vector type, was 'NULL'"; if I use "Seurat_preprocessing" function, the R studio will be aborted when running "Scissor" function. So could you help me debug these issues please? Thanks so much!

**Comment by Eddylyf** [comment]
By the way, I can run Scissor successfully using your example data.

**Comment by sunduanchen** [comment]
Can you send me your data and let me debug it?

Best,
Duanchen

**Comment by sunduanchen** [comment]
For your data privacy, you can send me a subset of your data, if it is available.

**Comment by sunduanchen** [comment]
Can you send me your data and let me debug it? For your data privacy, you can send me a subset of your data, if it is available.

Best,
Duanchen

**Comment by Eddylyf** [comment]
Sure! Could you please provide me a email address? Thanks a lot!
Best,
Yanfang

**Comment by sunduanchen** [comment]
sunduanchen@gmail.com

**Comment by Eddylyf** [comment]
Hi Duanchen,
I am sorry that my email cannot deliver to you which may due to the email server limits. Even all my files are less than 50M. Thanks again!
Best,
Yanfang

**Comment by sunduanchen** [comment]
You can try dropbox or other tools for sharing large files.

Best,
Duanchen

**Comment by hyjforesight** [comment]
dont use SCTransform. Use LogNormalize workflow.
