### ISSUE TITLE
Error in Scissor: There is no common genes between the given single-cell and bulk samples

### ISSUE THREAD

**Issue by ShiweiHePH** [sunduanchen/Scissor#19]
Hi, Scissor is a really useful and important tool of single cell data analysis, I really believe our team can found something new using your gorgeous R package.

I can run your tutorial data successfully, however, I got a error when using my data:

> infos4 <- Scissor(bulkdata, ScData, phenotype, tag = tag, alpha = 0.5, 
>                 family = "binomial", Save_file = "Scissor_disease.RData")
> 
> + Error in Scissor(bulkdata, ScData, phenotype, tag = tag, alpha = 0.5,  : 
> + **There is no common genes between the given single-cell and bulk samples.**

Can you help to figure out what happened there? Thanks a lot!

**Comment by ShiweiHePH** [comment]
By the way, our team's bulkseq samples and the single cell samples are the same species and disaese. But we still get the error: **no common genes between the given single-cell and bulk samples.**

**Comment by ShiweiHePH** [comment]
Thanks for your help!

**Comment by sunduanchen** [comment]
In the required single-cell and bulk expression matrix, rows are the genes and columns are the samples/cells. If the input format is correct, you can try toupper function in R to make sure that all genes are in upper case. 

If still not work, you can send me your data to debug it (my email address: sunduanchen@gmail.com).

Thanks,
Duanchen
