### ISSUE TITLE
Shall the alpha value be the same between Scissor() and reliability.test() functions?

### ISSUE THREAD

**Issue by hyjforesight** [sunduanchen/Scissor#23]
Hello Scissor,
I'm wondering whether the alpha value should be the same between the below 2 functions. According to your tutorial, we need to optimize the best alpha in `Scissor()`. Do we need to change it accordingly in `reliability.test()`?
`Scissor(bulk_dataset, sc_dataset, phenotype, tag = tag, alpha = 0.3, family = "binomial")`
`reliability.test(X, Y, network, alpha = 0.05, family = "binomial", cell_num = numbers, n = 100, nfold = 10)`
Thanks!
Best,
YJ

**Comment by sunduanchen** [comment]
Hi YJ,

Yes. You should use the optimized alpha in `reliability.test()`.

Best,
Duanchen
