### ISSUE TITLE
Some ideas about use our own seurat object

### ISSUE THREAD

**Issue by GuohuaZhu** [sunduanchen/Scissor#26]
Thanks for your wonderful packages. However, it seems unable to used at an integerated seurat object. After read the presubmited issues, I had know that the key parameters were 'data' and  ‘RNA_snn”； 
So，Could I change the "CCA_snn" (aquired by an integrated Seurat object) into 'RNA_snn' and use the RNA assy aquire 'data' slot?
Wishs for your reply. Thanks！

**Comment by sunduanchen** [comment]
I think so. You can have a try.

Thanks,
Duanchen

**Comment by GuohuaZhu** [comment]
Thanks for your reply. I had try it and finaly get a result at my local R studio, while it failed on my remote R studio sever

**Comment by jiexiong22** [comment]
> 
Hello！Thank you for your excellent idea, and I tried your idea in local R studio, but still reported a same error. Could you please share the code you changed?
Looking forward to your reply. Thanks!

**Comment by GGGGGHua** [comment]
If you had look through the source code of the Scissor function, you would find that the main input this function needs is the RNA data of the Seurat object and its graph@RNA_snn object：
`sc_exprs <- as.matrix(sc_dataset@assays$RNA@data)
            network <- as.matrix(sc_dataset@graphs$RNA_snn)`
So，as  the Seurat object RNA assay containing data，then we just need to assign 'CAA_snn' inside the integration object to 'RNA_snn'
` sc_dataset@graphs$RNA_snn <- sc_dataset@graphs$integrated_snn`
Then you can run the function.

**Comment by GGGGGHua** [comment]
If you had look through the source code of the Scissor function, you would find that the main input this function needs is the RNA data of the Seurat object and its graph@RNA_snn object：
sc_exprs <- as.matrix(sc_dataset@assays$RNA@data) network <- as.matrix(sc_dataset@graphs$RNA_snn)
So，as the Seurat object RNA assay containing data，then we just need to assign 'CAA_snn' inside the integration object to 'RNA_snn'
sc_dataset@graphs$RNA_snn <- sc_dataset@graphs$integrated_snn
Then you can run the function.

**Comment by GuohuaZhu** [comment]
> > 
> 
> Hello！Thank you for your excellent idea, and I tried your idea in local R studio, but still reported a same error. Could you please share the code you changed? Looking forward to your reply. Thanks!

If you had look through the source code of the Scissor function, you would find that the main input this function needs is the RNA data of the Seurat object and its graph@RNA_snn object：
`sc_exprs <- as.matrix(sc_dataset@assays$RNA@data)`
` network <- as.matrix(sc_dataset@graphs$RNA_snn)`
So，as the Seurat object RNA assay containing data，then we just need to assign 'CCA_snn' inside the integration object to 'RNA_snn'
`sc_dataset@graphs$RNA_snn <- sc_dataset@graphs$integrated_snn`
Then you can run the function.

**Comment by Dr-Xiong** [comment]
Thank you for your reply！ Your suggestions helped me solve the problem.

**Comment by jiexiong22** [comment]
> > Hello！Thank you for your excellent idea, and I tried your idea in local R studio, but still reported a same error. Could you please share the code you changed? Looking forward to your reply. Thanks!
> 
> If you had look through the source code of the Scissor function, you would find that the main input this function needs is the RNA data of the Seurat object and its graph@RNA_snn object： `sc_exprs <- as.matrix(sc_dataset@assays$RNA@data)` ` network <- as.matrix(sc_dataset@graphs$RNA_snn)` So，as the Seurat object RNA assay containing data，then we just need to assign 'CCA_snn' inside the integration object to 'RNA_snn' `sc_dataset@graphs$RNA_snn <- sc_dataset@graphs$integrated_snn` Then you can run the function.

Thank you for your reply！ Your suggestions helped me solve the problem.
