### ISSUE TITLE
Some problem about the input file for scissor with mutation information

### ISSUE THREAD

**Issue by YYYYYWWWYYYYYY** [sunduanchen/Scissor#30]
Hello developers,
I have some problem when i use scissor.I try to use scissor to choose cancer cell related to EGFR mutation in LUAD samples.I choose random several samples as a whole rds as input file and i have a result. Meanwhile,  i use these samples dependent rds and have others result. Its confusing that the two result are quite different and scissor choose more than 50 positive and negative cells in each dependent rds.

Which type of rds should i use as the input file for scissor?
Looking forward your reply

Thank you very much!

**Comment by sunduanchen** [comment]
Hi,

I'm not quite clear about your question. Why you choose random (bulk?) samples here? In real data applications, you can use all bulk samples as model input and save the preprocessed data as one RData file.

Could you please explain more details about your issue? 

Thanks,
Duanchen

**Comment by YYYYYWWWYYYYYY** [comment]
> Hi,
> 
> I'm not quite clear about your question. Why you choose random (bulk?) samples here? In real data applications, you can use all bulk samples as model input and save the preprocessed data as one RData file.
> 
> Could you please explain more details about your issue?
> 
> Thanks, Duanchen

Hi,
Im sorry not state the problem clearly.Not the bulk data, I choose single cell samples randomly.Like this,when I used 5 samples as a whole ,I got:
![lQLPDhtdYkiyR9HMi80BQbDZNWJAUFA_rQJprGSZAAUA_321_139](https://user-images.githubusercontent.com/103932475/165070037-512279ca-92f1-49ea-ac6c-746a7450ca85.png)
In this picture I used 5 samples as a whole rds as the input file. 
However in the next picture, I used 5 denpendent rds as the input files, and I also got results of these samples.
![D9964A67-FB83-41C7-8777-A918D8685948](https://user-images.githubusercontent.com/103932475/165093826-153a4abe-6144-4c43-aafd-0628d0c9d2d8.png)

 For example in P13 dependent rds, I got more than expected positive mutation cells.

**Comment by sunduanchen** [comment]
Hi,

Considering the underlying batch effects of samples and differences in single-cell experiments, the identification results differ in different input data is possible. Scissor+ cells that correspond to a given phenotype are a relative concept when compared with another phenotype. So it is also possible to have different numbers of Scissor+/- cells from the cells derived from one or a group of sequencing samples. 

Hope these help.

Best,
Duanchen
