### ISSUE TITLE
log2TPM or TPM?

### ISSUE THREAD

**Issue by liumoLM** [sunduanchen/Scissor#32]
Hi,

Thank you for developing this great tool.

Do you recommend log2TPM or TPM for bulk RNA seq data? I think this results in different phenotype association.

Thanks!

**Comment by sunduanchen** [comment]
Hi,

Based on our results, I think you can use TPM for bulk RNA-seq data.

Best,
Duanchen

**Comment by liumoLM** [comment]
Great. Thanks for your reply.

All the best,
Mo
