### ISSUE TITLE
The scissor package cannot be installed

### ISSUE THREAD

**Issue by master-XS** [sunduanchen/Scissor#4]
Hi
I followed the instructions to install the scissor package and reported an error
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/18435/AppData/Local/Temp/RtmpULhMMS/file3a305c6965d3/Scissor_2.0.0.tar.gz’ had non-zero exit status

can you help me resolve  the problem?

**Comment by eijynagai** [comment]
Hi, 

I'm not from the dev team, but I just installed the tool here.
`devtools::install_github('sunduanchen/Scissor')`

Perhaps you need to update your R or install devtools `devtools::install_github("hadley/devtools")`.

hope you can get it done.

Eijy
