### ISSUE TITLE
Can Scissor used for multiple subgroup ?

### ISSUE THREAD

**Issue by Phoenix12580** [sunduanchen/Scissor#43]
Thank you very much for your elegant tool!
I have a multiple subgroup and want to use Scissor for identifing different groups related cells, how should I use this tool?

Thank you again!

**Comment by sunduanchen** [comment]
Hi

This is a multi-classification. Since Scissor implemented logistic
regression for classification, you can use any multi-classification
strategies (such as one-vs-rest, one-vs-one) in supervised learning to
achieve your goal.

Best,
Duanchen

**Comment by Phoenix12580** [comment]
Thank you for your reply, i will try it
