### ISSUE TITLE
Test data link does not work

### ISSUE THREAD

**Issue by eijynagai** [sunduanchen/Scissor#5]
Hi, 

Thank you so much for developing Scissor! 
I just read the paper and wanted to try the tool before testing in my own data.

I couldn't download the dataset for the test. I got this error:

```
Warning message in load(url(paste0(location, "scRNA-seq.RData"))):
“URL 'https://xialab.s3-us-west-2.amazonaws.com/Duanchen/Scissor_data/scRNA-seq.RData': Timeout of 60 seconds was reached”
Error in load(url(paste0(location, "scRNA-seq.RData"))): cannot read from connection
Traceback:

1. load(url(paste0(location, "scRNA-seq.RData")))
```

I appreciate your time.

Best regards,

Eijy

**Comment by sunduanchen** [comment]
Hi Eijy,

I double checked the link and run the same code. I can load these test data properly. Can you try one more time or another network?

If you still cannot load. I can send you these data through other tools, e.g. dropbox.

Best,
Duanchen

**Comment by eijynagai** [comment]
Hi Duanchen,

Thank you for double-checking the link.

The problem is actually here. The time to download was superior to the limit allowed, so I needed to increase the time:
`options(timeout = 300) `

After altering that, it worked like a charm! So, nothing to do with Scissor.

I'm closing the issue.

Eijy
