### ISSUE TITLE
The length differs between tags and phenotypes. Please check Scissor inputs and selected regression type.

### ISSUE THREAD

**Issue by Jinjin89** [sunduanchen/Scissor#52]
I was tring using Scissor with gaussian family, my input phenotype is a numeric vector(length is 176), As I am concerned, the tag may be should be a name (whose length should be 1).  And it gives the length  error as the title suggests.

I turned to the source code found that
```
    if (family == "gaussian") {
      Y <- as.numeric(phenotype)
      z <- table(Y)
      if (length(z) != length(tag)) {
        stop("The length differs between tags and phenotypes. Please check Scissor inputs and selected regression type.")
      }
      else {
        tmp <- paste(z, tag)
        print(paste0("Current phenotype contains ", 
          paste(tmp[1:(length(z) - 1)], collapse = ", "), 
          ", and ", tmp[length(z)], " samples."))
        print("Perform linear regression on the given phenotypes:")
      }
    }
```

I am confused by the applying the table function for phenotype. It does make sense in logistic regression. However, I am not sure why use it in gaussian kernel.

Really appreciate any explaination

**Comment by sunduanchen** [comment]
Hi. You are right. Thanks for your suggestion. You can use any vector as
tag (length 176) for now and I will update the part soon.

Best,
Duanchen
