### ISSUE TITLE
Error in normalize.quantiles(dataset0) :ERROR; return code from pthread_create() is 22

### ISSUE THREAD

**Issue by skyfall-lyc** [sunduanchen/Scissor#7]
Hi,
Thank you so much for developing Scissor! 
I prepaer to explore the Scissor when I read your paper.
I encounted an error in this step:
**infos1 <- Scissor(bulk_dataset, sc_dataset, phenotype, alpha = 0.05, family = "cox", Save_file = 'Scissor_LUAD_survival.RData')
Error in normalize.quantiles(dataset0) : ERROR; return code from pthread_create() is 22**
Any suggestions would be greatly appreciated! Thank you for your time!
Best regards,
skyfall !

**Comment by skyfall-lyc** [comment]
> Hi, Thank you so much for developing Scissor! I prepaer to explore the Scissor when I read your paper. I encounted an error in this step: **infos1 <- Scissor(bulk_dataset, sc_dataset, phenotype, alpha = 0.05, family = "cox", Save_file = 'Scissor_LUAD_survival.RData') Error in normalize.quantiles(dataset0) : ERROR; return code from pthread_create() is 22** Any suggestions would be greatly appreciated! Thank you for your time! Best regards, skyfall !

I found the solution in https://github.com/Bioconductor/bioconductor_docker/issues/11

**Comment by skyfall-lyc** [comment]
> Hi, Thank you so much for developing Scissor! I prepaer to explore the Scissor when I read your paper. I encounted an error in this step: **infos1 <- Scissor(bulk_dataset, sc_dataset, phenotype, alpha = 0.05, family = "cox", Save_file = 'Scissor_LUAD_survival.RData') Error in normalize.quantiles(dataset0) : ERROR; return code from pthread_create() is 22** Any suggestions would be greatly appreciated! Thank you for your time! Best regards, skyfall !

I found the solution in https://github.com/Bioconductor/bioconductor_docker/issues/22

**Comment by leolambb** [comment]
Hi, the solution you provived here could not fix  the problem in my case. Is there other ways to fix this error? Thanks in advance.

 Best,
Leo Lam

**Comment by qi-shen** [comment]
I have the same error

**Comment by kefu007** [comment]
I also have the same  question
