### ISSUE TITLE
Error in normalize.quantiles(dataset0) :    ERROR; return code from pthread_create() is 22

### ISSUE THREAD

**Issue by yingqingdeng** [sunduanchen/Scissor#8]
Hi,
I have download the dataset, and want to try the scssior tool  with the test data.  However when I follow the Scissor_Tutorial,  using the comannd like this :  infos1 <- Scissor(bulk_dataset, sc_dataset, phenotype, alpha = 0.05, 
                 family = "cox", Save_file = 'Scissor_LUAD_survival.RData')

I have encounted the erro: 
Error in normalize.quantiles(dataset0) : ERROR; return code from pthread_create() is 22

I appreciate your time.
Best regards,
Qing

**Comment by chenx9** [comment]
Hello, I have the same problem, how do you solve this problem?
